### ISSUE TITLE
Sidenav naming convention User experience and Uptime 

### ISSUE THREAD

**Issue by liciavale** [elastic/observability-design#60]
## Summary of the problem
With the implementation of the new nav side, we’ll have an Overview Observability page. 

This means we can't use the name Overview and weed to find different names for these two links in the side nav. 

User experience: Dashboard/Overview
Uptime: Monitoring overview

**Comment by katrin-freihofner** [comment]
I suggest avoiding `Overview` as we already have the Observability overview.

**Comment by formgeist** [comment]
My suggestion would be to rename to;

<img width="172" alt="Screenshot 2021-06-23 at 10 54 36" src="https://user-images.githubusercontent.com/4104278/123067596-69d48500-d411-11eb-9a2c-913072ca8dc7.png">

Dashboard: because (surprise!) the view is a Dashboard of visualizations and breakdowns.
Monitors: as that's what they called and similarly to APM services and traces, we use the plural for these types of entities.

**Comment by formgeist** [comment]
The only possible roadblock for renaming the Uptime view to "Monitors" is the amount of "monitors" labels we have on the page.

<img width="540" alt="Screenshot 2021-06-23 at 11 33 39" src="https://user-images.githubusercontent.com/4104278/123073686-ee75d200-d416-11eb-9fc1-271530b504e7.png">

**Comment by drewpost** [comment]
I think the naming convention proposed by @formgeist works well. We want to migrate to a combined UI anyways starting in a 3-4 release timeframe and I don't think the names proposed cause any issue in the meantime.

**Comment by formgeist** [comment]
@drewpost Thank you for the feedback 👍 @liciavale Will you be comfortable creating the PR updating the labels in Kibana?
